import type { Collection } from "./types";

export const initialCollections: Collection[] = [
  {
    id: "jamie",
    name: "Jamie Rhee",
    date: "22nd August, 2024",
    label: "Summer Collection",
    photos: ["/photos/jamie.png"],
    position: { x: 280, y: 123 },
    size: { w: 200, h: 209 },
    state: "normal",
    photoIndex: 0,
    z: 1,
  },
  {
    id: "anthony",
    name: "Anthony",
    date: "1st January, 2025",
    photos: ["/photos/anthony.png"],
    position: { x: 547, y: 93 },
    size: { w: 180, h: 180 },
    state: "normal",
    photoIndex: 0,
    z: 2,
  },
  {
    id: "eliza",
    name: "Eliza Stone",
    date: "14th July, 2024",
    label: "Coastal Dreams",
    photos: [],
    position: { x: 152, y: 386 },
    size: { w: 198, h: 207 },
    state: "normal",
    photoIndex: 0,
    z: 3,
  },
  {
    id: "hazel",
    name: "Hazel Bloom",
    date: "1st January, 2025",
    photos: ["/photos/hazel.png"],
    position: { x: 389, y: 476 },
    size: { w: 250, h: 350 },
    state: "normal",
    photoIndex: 0,
    z: 4,
  },
  {
    id: "layla",
    name: "Layla Banks",
    date: "17th March, 2025",
    photos: ["/photos/layla.png"],
    position: { x: 681, y: 306 },
    size: { w: 200, h: 270 },
    state: "normal",
    photoIndex: 0,
    z: 5,
  },
];
